# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-AutoSession
version:      0.02
version_from: AutoSession.pm
installdirs:  site
requires:
    Catalyst:                      2.99

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
